# Generated by Django 5.1.3 on 2024-11-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(verbose_name='Телеграм id')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('is_subscription', models.BooleanField(default=True, verbose_name='Подписан на рассылку')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фирмы товара')),
            ],
            options={
                'verbose_name': 'Фирма производитель',
                'verbose_name_plural': 'Фирмы производитель',
                'db_table': 'manufacturer_companies',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа товара')),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продукта',
                'db_table': 'products_types',
            },
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подтипа')),
                ('manufacturer_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.manufacturercompany', verbose_name='Фирма производитель')),
                ('products_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.producttype', verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Подтип',
                'verbose_name_plural': 'Подтипы',
                'db_table': 'Subtype',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.subtype', verbose_name='Подтип')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'Product',
            },
        ),
    ]
