# Generated by Django 5.1.3 on 2025-10-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtype',
            name='manufacturer_company',
        ),
        migrations.RemoveField(
            model_name='subtype',
            name='products_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.producttype', verbose_name='Тип продукта'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Позже появится', verbose_name='Описание товара(Что выведется при нажатии)'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название типа товара(что будет написано на кнопке)'),
        ),
        migrations.DeleteModel(
            name='ManufacturerCompany',
        ),
        migrations.DeleteModel(
            name='Subtype',
        ),
    ]
